config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :todos
  end

  root to: 'todos#home'
end

app/models/application_record.rb
# :nodoc:
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
# :nodoc:
class Todo < ApplicationRecord
  validates :title, presence: true, length: { maximum: 20 }

  validates :description, presence: true, length: { maximum: 150 }

  belongs_to :user
end

app/models/user.rb
# :nodoc:
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todos
end

app/controllers/application_controller.rb
# :nodoc:
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
# :nodoc:
class TodosController < ApplicationController
  before_action :authenticate_user!, except: [:home]

  def index
    @user = User.find(params[:user_id])
    @todos = @user.todos
  end

  def show
    @user = User.find(params[:user_id])
    @todo = @user.todos.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @todo = Todo.new
  end

  def create
    @user = User.find(params[:user_id])
    @todo = @user.todos.create(todo_params)

    if @todo.save
      redirect_to user_todos_path(current_user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @todo = @user.todos.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @todo = @user.todos.update(todo_params)

    if @todo
      redirect_to user_todos_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @todo = @user.todos.find(params[:id])

    if @todo.destroy
      redirect_to user_todos_path(current_user)
    else
      render 'show'
    end
  end

  def home; end

  private

  def todo_params
    params.require(:todo).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
# :nodoc:
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <%= render 'shared/navbar' %>
    <%= csrf_meta_tags %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="http://localhost:3000/">Todo App</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-md-auto">

          <li class="nav-item active">
            <%= link_to "Home", root_path, class: 'nav-link' %>
          </li>

          <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My Todos", user_todos_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to "New Todo", new_user_todo_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
          <% else %>
          <li class="nav-item active">
            <%= link_to "Sign Up", new_user_registration_path,  class: 'nav-link' %>
          </li>
          <li class="nav-item active">
          <%= link_to "Sign In", new_user_session_path,  class: 'nav-link' %>
          </li>
          <% end %>
      </div>
  </nav>

app/views/todos/edit.html.erb
<div class = "text-center">

    <%= form_with model: ([@user, @todo]) do |f| %>

        <div class = "container">

            

                <div class = "form-group">
                    <%= f.text_field :title, class: "form-control", placeholder: "title" %>
                </div>

                <div class = "form-group">
                    <%= f.text_area :description, class: "form-control", placeholder: "description" %>
                </div>

                <%= f.submit "Update", class: "btn btn-primary" %>
            

            
        
        </div>

    <% end %>

</div>

app/views/todos/home.html.erb
<% if user_signed_in? %>

<div class = "card">
  <div class = "text-center">
    <div class="card" style="width: 38rem;">
      <%= image_tag('home.jpg', class: 'card-img-top') %>
    <div class="card-body">
      <h5 class="card-title">You are logged in!</h5>
      <p class="card-text">We are happy that you use our site, enjoy!</p>
      <%= link_to "Make new Todo", new_user_todo_path(current_user),  class: "btn btn-primary" %>
    </div>
    </div>
  </div>
</div>

<% else %>

<div class = "card">
  <div class = "text-center">
    <div class="card" style="width: 38rem;">
      <%= image_tag('home.jpg', class: 'card-img-top') %>
    <div class="card-body">
      <h5 class="card-title">Create your own To do list!</h5>
      <p class="card-text">Sign up now! Everything is free for logged users, join to us!</p> 
      <%= link_to "Sign Up!", new_user_registration_path,  class: "btn btn-primary" %>
    </div>
    </div>
  </div>
</div>

<% end %> 

app/views/todos/index.html.erb
<div class = "container" >
  <div class = "row">

    <% @user.todos.each do |f| %>

      <div class = "col-md-3">
      
      <div class="card" style="width: 10rem;">
        <%= image_tag('tick.png', class: 'card-img-top') %>
      <div class="card-body">
        <div class="text-center">
          <h5 class="card-title"><%= f.title %> </h5>
          <%= link_to "Show", user_todo_path(current_user, f),  class: "btn btn-primary" %>
        </div>
      </div>
      </div>

      </div>

  <% end %>

  </div>
</div>

app/views/todos/new.html.erb
<div class = "text-center">

    <%= form_with model: ([@user, @todo]) do |f| %>

        <% if @todo.errors.any? %>
            <% @todo.errors.full_messages.each do |message| %>     
                <li><%= message %></li>
            <% end %>
        <% end %> 
        

    <div class = "container">

        

            <div class = "form-group">
                <%= f.text_field :title, class: "form-control", placeholder: "title" %>
            </div>

            <div class = "form-group">
                <%= f.text_area :description, class: "form-control", placeholder: "description" %>
            </div>

            <%= f.submit "Submit", class: "btn btn-primary" %>
        

        
    
    </div>

    <% end %>

</div>

app/views/todos/show.html.erb
<div class = "text-center"
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= @todo.title %></li>
        <li class="list-group-item"><%= @todo.description %></li>

        <%= link_to "Done", user_todo_path, method: :delete, class: 'btn btn-primary' %>
        <%= link_to "Edit", edit_user_todo_path(current_user, @todo), class: 'btn btn-primary' %>
        <%= link_to "Back", user_todos_path(current_user, @todo), class: 'btn btn-primary' %>
    <ul>
</div>